### ISSUE TITLE
Unable to run even the sample

### ISSUE THREAD

**Issue by nicolabeghin** [gravity00/SimpleSOAPClient#32] opened 2017-07-10 09:40 UTC
Hi everyone
I would like to understand if I'm the only one experiencing this issue, preventing me from using the library at all. At some point I even copied the sample code, and it still doesn't work

```cs
SoapEnvelope responseEnvelope;
try
{
	string clearTextCredentials = string.Format("{0}:{1}", SAP_USERNAME, SAP_PASSWORD);
	client.HttpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(Encoding.UTF8.GetBytes(clearTextCredentials)));
	responseEnvelope =
		await client.SendAsync(
			BASE_URL + ENDPOINT_ZUB_LETTURAEVE_BND,
			"testing",
			new SoapEnvelope()
				.WithHeaders(new TrackingHeader())
				.Body(new CreateUserRequest() { Username = "Prova", Password = "prova" }));
}
catch (SoapEnvelopeSerializationException e)
{
	Debug.WriteLine("Failed to serialize the SOAP Envelope"+e.Message);
}
catch (SoapEnvelopeDeserializationException e)
{
	Debug.WriteLine("Failed to deserialize the response into a SOAP Envelope" + e.Message);
}
catch (Exception e)
{
	Debug.WriteLine("General exception: " + e.Message);
}
```

Below the stacktrace
```
  at SimpleSOAPClient.SoapEnvelopeSerializationProvider.ToXmlString (SimpleSOAPClient.Models.SoapEnvelope envelope) [0x0005a] in <42f699401f4c42a2bbfcc53c5849d324>:0 
  at SimpleSOAPClient.SoapClient+<SendAsync>d__20.MoveNext () [0x00136] in <42f699401f4c42a2bbfcc53c5849d324>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at BocconiNetworkServices.Networking.SAPService+<prova2>d__12.MoveNext () [0x000f2] in C:\BocconiDeskApp\BocconiNetworkServices\Networking\SAPService.cs:54 
```

Please note I'm using SimpleSoapClient in a PCL project.
![image 4](https://user-images.githubusercontent.com/2743637/28011897-41cd3072-6564-11e7-8c54-7281da318912.png)

thanks
nicola

**Comment by gravity00** [comment] 2017-07-10 09:53
@nicolabeghin can you show me that `TrackingHeader` and `CreateUserRequest` classes? Also, is that all the stacktrace with the message?

**Comment by nicolabeghin** [comment] 2017-07-10 09:57
hi @gravity00 thanks for your fast reply! 
Here's the classes
```cs
[XmlRoot("Tracking", Namespace = "http://services.company.com")]
public class TrackingHeader : SimpleSOAPClient.Models.SoapHeader
{
	[XmlElement("Id")]
	public Guid Id { get; set; }

	[XmlElement("CreatedOn")]
	public DateTime CreatedOn { get; set; }

	public TrackingHeader()
	{
		MustUnderstand = 0; // this is the default value
	}
}

[XmlRoot("CreateUserRequest", Namespace = "http://services.company.com")]
public class CreateUserRequest
{
	[XmlElement("Username")]
	public string Username { get; set; }

	[XmlElement("Password")]
	public string Password { get; set; }
}
```

Also more stacktrace (I'm debugging the code). 
```
  at System.Xml.Serialization.XmlSerializer.Serialize (System.Xml.XmlWriter xmlWriter, System.Object o, System.Xml.Serialization.XmlSerializerNamespaces namespaces) [0x00093] in <69fb168feda3422cb50a9a4f302b574c>:0 
  at SimpleSOAPClient.SoapEnvelopeSerializationProvider.ToXmlString (SimpleSOAPClient.Models.SoapEnvelope envelope) [0x00023] in C:\BocconiDeskApp\SimpleSOAPClient\SimpleSOAPClient\SoapEnvelopeSerializationProvider.cs:101 
```

![image 5](https://user-images.githubusercontent.com/2743637/28012660-d2b559c8-6566-11e7-8d80-b9efa364721c.png)

**Comment by gravity00** [comment] 2017-07-10 10:03
@nicolabeghin the classes look ok. It seems there is an inner exception. Can you send me the `e.ToString()` value? This should be enough for me to get a better understanding.

**Comment by nicolabeghin** [comment] 2017-07-10 10:10
Here it is

`[0:] SimpleSOAPClient.Exceptions.SoapEnvelopeSerializationException: Failed to serialize the SOAP Envelope ---> System.InvalidOperationException: There was an error generating the XML document. ---> System.InvalidOperationException: XmlAnyElementAttribute can only be applied to members of type XmlElement, XmlElement[] or XmlNode[]. The target object is System.Xml.Linq.XElement`

**Comment by gravity00** [comment] 2017-07-10 10:32
@nicolabeghin I made a fast test with you classes and I could get the expected XML based on your example.

```xml
<q1:Envelope xmlns:q1="http://schemas.xmlsoap.org/soap/envelope/">
  <q1:Header>
    <q1:Tracking p1:mustUnderstand="0" xmlns:p1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:q1="http://services.company.com">
      <q1:Id>00000000-0000-0000-0000-000000000000</q1:Id>
      <q1:CreatedOn>0001-01-01T00:00:00</q1:CreatedOn>
    </q1:Tracking>
  </q1:Header>
  <q1:Body>
    <q1:CreateUserRequest xmlns:q1="http://services.company.com">
      <q1:Username>Prova</q1:Username>
      <q1:Password>prova</q1:Password>
    </q1:CreateUserRequest>
  </q1:Body>
</q1:Envelope>
```

If you do the following, does it also fail?

```csharp
using (var client = SoapClient.Prepare())
{
    //  just to indent the XML
    ((SoapEnvelopeSerializationProvider) client.Settings.SerializationProvider)
        .XmlWriterSettings.Indent = true;

    var envelope = SoapEnvelope.Prepare()
        .WithHeaders(new TrackingHeader())
        .Body(new CreateUserRequest
        {
            Username = "Prova",
            Password = "prova"
        });

    // the exception should happen here
    var xml = client.Settings.SerializationProvider.ToXmlString(envelope);
}
```

**Comment by nicolabeghin** [comment] 2017-07-10 10:48
I confirm, the exception happens exactly where expected (as shown by the stacktrace too). any idea on why this happens? Maybe because it's a PCL?

**Comment by nicolabeghin** [comment] 2017-07-10 10:54
btw could you share the list of your references from the original project or a PCL that's working for you? I can't open the VS2015 project, so I copied the sources to a brand new PCL.

![image 8](https://user-images.githubusercontent.com/2743637/28015089-d4267fa0-656e-11e7-89d4-00811a4db0cf.png)


thanks
nicola

**Comment by gravity00** [comment] 2017-07-10 11:12
@nicolabeghin yes, it looks like the problem is some limitation for XML serialization support in PCL projects (my test was in a .NET 4.6 console, just to see the behavior). I'll need to make some tests in a PCL project, but it looks like I'll certainly need to create conditional code compilation depending of framework.

If I look at [`XmlAnyElement`](https://msdn.microsoft.com/en-us/library/system.xml.serialization.xmlanyelementattribute.aspx) documentation, clearly the support to `XElement` was added, but some older frameworks may lack the support (looking at your list, maybe W8 or WP8.1?).

> When working in a portable class library, such as in Silverlight, Windows Phone or Windows Store App project, and you are using the .NET Framework 4.0.3 and above, use XElement or XNode in place of XmlElement and XmlNode.

Just to test, could you uncheck those frameworks from the list, just to see if it still fails?

**Comment by nicolabeghin** [comment] 2017-07-10 13:15
hi @gravity00 I tried creating a PCL based on 4.6 but for some reason VS2017 created it for .NET 4.5. At the same time it doesn't let me remove any platform target, even after removing all nuget packages. it's becoming a nightmare :-/

**Comment by gravity00** [comment] 2017-07-10 13:30
@nicolabeghin I've used this library in Xamarin Android and iOS applications without a problem, but never on Windows Phones, so never detected this problem sooner.

I'm able to do some testings now, let me look into it.

**Comment by nicolabeghin** [comment] 2017-07-10 13:43
thanks @gravity00, really appreciate. I'm trying to move the whole thing out of the PCL and into the Android project, as I don't see any other way around.

**Comment by gravity00** [comment] 2017-07-10 14:11
@nicolabeghin I was trying to create a Xamarin Forms application, but my current computer doesn't have anything installed. I'll have to wait until I get home. In the meantime, have you tried a Shared Project instead of a PCL? Unless you want to reuse your library for other applications, this may be enough for your case.

I have tried to create some PCL library and then test it, but these libraries are a pain to test without having an emulator installed.

Edit: Also, I support .NET Standard 1.1 and up. Maybe you can use it instead of a PCL. To my knowledge, it should be compatible with the iOS, Android and Windows projects for those versions.

**Comment by nicolabeghin** [comment] 2017-07-10 14:22
thanks @gravity00 but it doesn't work even in the Android project. I removed all PCL and shared projects, same issue and exception.

> Failed to serialize the SOAP Envelope

![image 10](https://user-images.githubusercontent.com/2743637/28022493-a6074ea2-658b-11e7-8336-9e1584f07f34.png)

```
  at SimpleSOAPClient.SoapEnvelopeSerializationProvider.ToXmlString (SimpleSOAPClient.Models.SoapEnvelope envelope) [0x0005a] in <b95603d8ac1a402283b3bb9c2ca2a295>:0 
  at SimpleSOAPClient.SoapClient+<SendAsync>d__20.MoveNext () [0x00136] in <b95603d8ac1a402283b3bb9c2ca2a295>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
  at BocconiDeskApp.Droid.Networking.TestSoapClient+<prova2>d__12.MoveNext () [0x000dc] in C:\BocconiDeskApp\BocconiDeskApp\BocconiDeskApp.Android\Networking\TestSoapClient.cs:50 
```

**Comment by gravity00** [comment] 2017-07-10 15:02
@nicolabeghin this is definitely a bug, I'll look into it as soon as I get home. In the mean time I believe I can create a work around. Because it is a serialization problem, I may be able to create a custom `ISoapEnvelopeSerializationProvider` that will work in a PCL project. Just let me make some tests and I'll give you a sample.

The idea would be to receive the `SoapEnvelope` or XML string and use a custom `SoapEnvelope` that uses `XmlElement` instead of `XElement` for the body and headers.

**Comment by nicolabeghin** [comment] 2017-07-10 15:06
@gravity00 you would be my hero! I'm near depression to get this thing sorted out.. :-D

**Comment by gravity00** [comment] 2017-07-10 16:22
@nicolabeghin ok, I believe I have something that should fix your problem, at least for now. Create the following custom `ISoapEnvelopeSerializationProvider` and assign it to your client. Internally it uses classes with `XmlElement` instances for the body and headers.

```csharp
public class PclSoapEnvelopeSerializationProvider : ISoapEnvelopeSerializationProvider
{
    public SoapEnvelopeSerializationProvider InternalProvider { get; } = new SoapEnvelopeSerializationProvider();

    #region Implementation of ISoapEnvelopeSerializationProvider

    /// <inheritdoc />
    public string ToXmlString(SoapEnvelope envelope)
    {
        if (envelope == null)
            return null;

        var innerEnvelope = new PclSoapEnvelope
        {
            Body = ToPclSoapEnvelopeBody(envelope.Body),
            Header = ToPclSoapEnvelopeHeader(envelope.Header)
        };

        try
        {
            using (var textWriter = new StringWriter())
            using (var xmlWriter = XmlWriter.Create(textWriter, InternalProvider.XmlWriterSettings))
            {
                new XmlSerializer(typeof(PclSoapEnvelope))
                    .Serialize(xmlWriter, innerEnvelope, InternalProvider.XmlSerializerNamespaces);
                return textWriter.ToString();
            }
        }
        catch (Exception e)
        {
            throw new SoapEnvelopeSerializationException(envelope, e);
        }
    }

    /// <inheritdoc />
    public SoapEnvelope ToSoapEnvelope(string xml)
    {
        if (string.IsNullOrWhiteSpace(xml))
            return null;

        try
        {
            using (var textWriter = new StringReader(xml))
            {
                var result = (PclSoapEnvelope)
                    new XmlSerializer(typeof(PclSoapEnvelope)).Deserialize(textWriter);

                return result == null
                    ? null
                    : new SoapEnvelope
                    {
                        Body = ToSoapEnvelopeBody(result.Body),
                        Header = ToSoapEnvelopeHeader(result.Header)
                    };
            }
        }
        catch (Exception e)
        {
            throw new SoapEnvelopeDeserializationException(xml, e);
        }
    }

    #endregion

    #region Mappers

    private static PclSoapEnvelopeBody ToPclSoapEnvelopeBody(SoapEnvelopeBody body)
    {
        if (body == null)
            return null;

        var pclBody = new PclSoapEnvelopeBody();
        if (body.Value == null)
            return pclBody;

        using (var reader = body.Value.CreateReader())
        {
            var doc = new XmlDocument();
            doc.Load(reader);
            pclBody.Value = doc.DocumentElement;
        }

        return pclBody;
    }

    private static PclSoapEnvelopeHeader ToPclSoapEnvelopeHeader(SoapEnvelopeHeader header)
    {
        if (header == null)
            return null;

        var pclHeader = new PclSoapEnvelopeHeader();
        if (header.Headers == null)
        {
            pclHeader.Headers = null;
        }
        else
        {
            pclHeader.Headers = new XmlElement[header.Headers.Length];
            for (var i = 0; i < pclHeader.Headers.Length; i++)
            {
                using (var reader = header.Headers[i].CreateReader())
                {
                    var doc = new XmlDocument();
                    doc.Load(reader);
                    pclHeader.Headers[i] = doc.DocumentElement;
                }
            }
        }

        return pclHeader;
    }

    private static SoapEnvelopeBody ToSoapEnvelopeBody(PclSoapEnvelopeBody pclBody)
    {
        if (pclBody == null)
            return null;

        return new SoapEnvelopeBody
        {
            Value = pclBody.Value == null
                ? null
                : XElement.Parse(pclBody.Value.OuterXml)
        };
    }

    private static SoapEnvelopeHeader ToSoapEnvelopeHeader(PclSoapEnvelopeHeader pclHeader)
    {
        if (pclHeader == null)
            return null;

        var header = new SoapEnvelopeHeader();
        if (pclHeader.Headers == null)
        {
            header.Headers = null;
        }
        else
        {
            header.Headers = new XElement[pclHeader.Headers.Length];
            for (var i = 0; i < pclHeader.Headers.Length; i++)
            {
                header.Headers[i] = XElement.Parse(pclHeader.Headers[i].OuterXml);
            }
        }

        return header;
    }

    #endregion
}

[XmlRoot("Envelope", Namespace = Constant.Namespace.OrgXmlSoapSchemasSoapEnvelope)]
public class PclSoapEnvelope
{
    [XmlElement("Body")]
    public PclSoapEnvelopeBody Body { get; set; }

    [XmlElement("Header")]
    public PclSoapEnvelopeHeader Header { get; set; }
}

public class PclSoapEnvelopeBody
{
    [XmlAnyElement]
    public XmlElement Value { get; set; }
}

public class PclSoapEnvelopeHeader
{
    [XmlAnyElement]
    public XmlElement[] Headers { get; set; }
}
```

Test code:

```csharp
var pclProvider = new PclSoapEnvelopeSerializationProvider();

// just to indent XML for testing
pclProvider.InternalProvider.XmlWriterSettings.Indent = true;

using (var client = SoapClient.Prepare())
{
    client.Settings.SerializationProvider = pclProvider;

    var envelope = SoapEnvelope.Prepare()
        .WithHeaders(new TrackingHeader())
        .Body(new CreateUserRequest
        {
            Username = "Prova",
            Password = "prova"
        });

    // the exception should be fixed now
    var xml = client.Settings.SerializationProvider.ToXmlString(envelope);

    // this envelope should be equal to the original
    var resultEnvelope = client.Settings.SerializationProvider.ToSoapEnvelope(xml);
}
```

**Comment by nicolabeghin** [comment] 2017-07-10 16:38
Thanks A LOT @gravity00. 
The strangest thing is happening: no XMLElement type is found when importing your code.
![image](https://user-images.githubusercontent.com/2743637/28028792-fa3d5d06-659d-11e7-9cee-54f286353550.png)

even if `packages.config` says it's installed

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="System.Linq" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="portable45-net45+win8+wpa81" />
</packages>
```

**Comment by nicolabeghin** [comment] 2017-07-10 16:45
If I understand correctly [from official Microsoft docs](https://msdn.microsoft.com/en-us/library/system.xml.serialization.xmlanyelementattribute.aspx#Anchor_6): in a PCL/UWP/cross-platform project it should be ok to use `XElement `in place of `XmlElement`
![image](https://user-images.githubusercontent.com/2743637/28029271-c4933e44-659f-11e7-94a4-daa7f0a2dc71.png)

**Comment by gravity00** [comment] 2017-07-10 16:52
@nicolabeghin the problem is that you are referencing Mono, by adding support to Android and iOS. These frameworks runs in an older version of .NET, which leads to this problem.

I just created a new PCL project, with just the default references, and I could reference the `XmlElement` from the namespace `System.Xml.Serialization`.

```csharp
using System.Xml.Serialization;

namespace SimpleSOAPClient.Test.Pcl
{
    public class TestClass
    {
        [XmlElement]
        public string Example { get; set; }
    }
}
```

![image](https://user-images.githubusercontent.com/3291285/28029564-5e575a4a-6598-11e7-88ed-3e43d6531af2.png)

**Comment by nicolabeghin** [comment] 2017-07-10 17:02
2 questions:

1. are you then able to use such PCL from a Xamarin.Android project? I get runtime errors.
2. did you try using the explicit type `System.Xml.XmlElement` and not the `[XmlElement]` attribute? I can use the `[XmlElement]` but not the type, therefore the issue with the new `PclSoapEnvelopeSerializationProvider`

![image](https://user-images.githubusercontent.com/2743637/28031714-79f2a90c-65a8-11e7-8eac-a8243bbded35.png)

**Comment by gravity00** [comment] 2017-07-11 08:30
@nicolabeghin my example was wrong, sorry. From my findings, `XmlElement` is not available in PCL but in your Xamarin Android project you have it. My suggestion is to create the custom `ISoapEnvelopeSerializationProvider` there and then use it in the PCL code using DI or when your code used the PCL, it replaces the default one. Can you give it a try?

**Comment by nicolabeghin** [comment] 2017-07-11 10:53
@gravity00 , YOU'RE THE MAN!!!! it works now! than you so much.
To make things clear for anyone facing the same issue:
- Shared Project containing the provided custom `PclSoapEnvelopeSerializationProvider` + networking code (in order to keep it cetral and avoid to duplicate for each platform)
- Xamarin.Android project referencing `System.Xml`, `System.Xml.Linq`, `System.Xml.Serialization`

![image](https://user-images.githubusercontent.com/2743637/28065112-834fffec-6637-11e7-8867-11865c240fa7.png)

ps any cetralized way to tell the `PclSoapEnvelopeSerializationProvider` to print all elements even the empty ones?

**Comment by gravity00** [comment] 2017-07-11 11:36
@nicolabeghin you are welcome. Now I'll have to try to include this fix inside the library, but it may not be possible.

About including empty elements in the XML, I believe there is no central way to do that (if there is, the `XmlWriterSettings` I used to indent the code should lead you to some solution) but if you enable the property `IsNullable` in the `XmlElementAttribute` I think it will include the node if null.

**Closed as completed** 2018-06-29 15:47 UTC
Labels: bug
